### ISSUE TITLE
Localization Support?

### ISSUE THREAD

**Issue by Kasualix** [isXander/MixinConflictHelper#8]
Like [here](https://github.com/isXander/MixinConflictHelper/blob/a72d8ef93de08499e7de8ccbe910b25a3e75ff05/src/main/java/dev/isxander/mixinconflicthelper/gui/SwingPopups.java#L60).
I want to translate this mod into Simplified Chinese, but it doesn't have a language file....

**Comment by isXander** [comment]
This is because Mixin Conflict Helper loads before Minecraft does, and therefore, its localisation features.
